# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: medical-record
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker.io/todorpopov02/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: AUTH_PORT
              value: "9091"
            - name: JWT_SECRET
              value: "Medrec JWT Secret (This key needs to be very very long, in order to maximize security, io.jwttoken will not start the process, unless the key is deemed secure enough.)"
            - name: USERS_PORT
              value: "9090"
            - name: USERS_HOST
              value: "users-service"
            - name: ADMIN_EMAIL
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "admin"
          livenessProbe:
            grpc:
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred

---

# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medical-record
spec:
  selector:
    app: auth-service
  ports:
    - port: 9091
      targetPort: 9091
  type: ClusterIP