# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: medical-record
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: frontend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---

# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: medical-record
spec:
  selector:
    app: frontend-service
  ports:
    - port: 4000
      targetPort: 80
  type: ClusterIP